-- Plan 1.5: extend audio-playback MIME whitelist to include WAV so the
-- Susheela hello-world greeting (generated by scripts/generate-susheela-hello.ts
-- from Sarvam TTS at 8 kHz PCM WAV) can be uploaded for Plivo to fetch.
UPDATE storage.buckets
SET allowed_mime_types = ARRAY[
  'audio/ogg',
  'audio/opus',
  'audio/mpeg',
  'audio/wav',
  'audio/wave',
  'audio/x-wav'
]
WHERE id = 'audio-playback';
